### ISSUE TITLE
release takeout 2.3.0.

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io-takeout#145]
Includes changes:
- [x]  mongo in takeout (#95)
- [x] port routing on host (waffleio/takeout-nginx#22)
- [x] remove CAAC integration (waffleio/waffle.io-takeout-management#145)
- [x] server side communication to Poxa is over `docker0` (https://github.com/waffleio/waffle.io-takeout/issues/150)

Bug Fixes:
- [x] join link doesn't work on takeout (waffleio/waffle.io-takeout#138)
- [x] Deep-linking to a takeout seems to not redirect to authenticate (waffleio/waffle.io-takeout#142)

Release steps:

- [x] update changelog
- [x] promote to stable

- [ ] after this is done, do waffleio/waffle.io-biz#542

**Comment by burtonjc** [comment]
Before we release 2.3.0 to stable, we should test the "require" release flow on unstable to make sure the replicated console does indeed require you install a given release before continuing on.

**Comment by homeyer** [comment]
- [ ] document how to save off your backups

**Comment by songawee** [comment]
re-enable GH:E and upgrade stable to monitor upgrade process
