### ISSUE TITLE
use beta.replicated.waffle.io for tracking Waffle for a week

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io-takeout#146]
Let's stress test the system a bit with mongo packaged in takeout by running our team off of it for a week.
- [x] use beta.replicated.waffle.io, once #95 is on the beta channel
- [x] configure the waffle board to match our prod board
- [ ] set up a page rule to redirect from SaaS to takeout for our board (lol just kidding)

**Comment by songawee** [comment]
https://beta.replicated.waffle.io/ has a beta release that includes the new mongodb changes
