### ISSUE TITLE
New Pay-What-You-Want pricing tier for Takeout, for teams with 15 or less users (proceeds go 100% to Code for America)

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io-takeout#96]
- [x] complete dev work located at https://github.com/waffleio/waffle.io-takeout-management/issues/84 (private)
- [ ] confirm update of pricing tiers and language at takeout.waffle.io 
- [ ] announce the new tier and our partnership with Code for America - tracking in https://github.com/waffleio/waffle.io-biz/issues/461 (private)

**Comment by homeyer** [comment]
create a milestone for this, and make sure we have appropriate cards for it

**Comment by homeyer** [comment]
milestone created! closing the epic :).
